### ISSUE TITLE
Doesn't appear to statically generate preview routes for Contentful

### ISSUE THREAD

**Issue by jonjahr** [BKWLD/cloak#54]
Steps to reproduce:

* Checkout HFO `main`
* Set your ENV to the Contentful Preview settings:
  * `APP_ENV=dev`
  * `CONTENTFUL_ACCESS_TOKEN=<the preview token>`
  * `CONTENTFUL_PREVIEW=true`
* Run `yarn generate`

Expected: Towers with [status=draft](https://app.contentful.com/spaces/nis7p59xqtob/environments/master/entries?id=qKQGACiIiH9dd1w2&contentTypeId=tower&order.fieldId=updatedAt&order.direction=descending&displayedFieldIds=updatedAt&roles=3mCSAZglfoSEFmZf8kZDxQ&folderId=AM7GI0qnY3aggc4k&page=1&filters.0.key=__status&filters.0.val=draft), such as  [demo-slide-marquee-block](https://app.contentful.com/spaces/nis7p59xqtob/environments/master/entries/6WRSn14kuyN34dSeRCejMO), should be generated.

Observed:  Draft towers don't get generated.

**Comment by jonjahr** [comment]
Side note, I just noticed HFO is using a branch version of cloak:
`"@bkwld/cloak": "https://github.com/BKWLD/cloak#add-fetchkey-prop-to-richtext"`

I upgraded to `1.15.x`, and it seems to work fine locally, but it doesn't fix this issue.

**Comment by weotch** [comment]
Ok, this is fixed in 1.15.3 if you wanna update to it.

--

Also, btw, you store the preview token in `process.env.CONTENTFUL_PREVIEW_ACCESS_TOKEN` and it will be used whenever `CONTENTFUL_PREVIEW=true` ... not really sure why I set it up that way at this point but should make it a little easier to switch to preview mode

https://github.com/BKWLD/cloak/blob/e5a12a7bce08c4a7153dbbf78a5c03caa27e6119/config/concerns/cms.coffee#L21-L26
