### ISSUE TITLE
Add credits package

### ISSUE THREAD

**Issue by weotch** [BKWLD/cloak#9]
https://github.com/BKWLD/credits

**Comment by weotch** [comment]
@jonjahr FYI, your Credits package now ships with Cloak, if you wanna update to this version on SXM

**Comment by jonjahr** [comment]
Sorry I haven't upgraded to cloak 1.1.0... I'm not ignoring you, it's
because I need this commit in the `1.x` branch.  Without the `limit:1000`,
Contentful only returns (and thus Nuxt only statically generates) the first
100 articles.   So I've got SXM pinned to this commit for now.
https://github.com/BKWLD/cloak/commit/06835d0bf8e5e10b6e27ac8850fe08ef268caa72
